name: Build
on:
  pull_request:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
    
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    - uses: ros-tooling/setup-ros@master
    - run: |
        ls -R
        mkdir -p ${GITHUB_WORKSPACE}/ros_ws/src/
        pushd ${GITHUB_WORKSPACE}/ros_ws/src/
        git clone -b master https://github.com/Kapernikov/cv_camera.git
        git clone -b ros2 https://github.com/ros-perception/image_common.git
        git clone -b ros2 https://github.com/ros-perception/vision_opencv.git
        popd
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: onnx_object_detection
        target-ros2-distro: foxy
    - uses: actions/upload-artifact@v1
      with:
        name: drop
        path: c:\opt\install
