name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-latest, windows-latest]
    steps:
    - uses: ros-tooling/setup-ros@0.0.15
    - uses: ros-tooling/action-ros-ci@master
      with:
        package-name: ros_msft_onnx
    - uses: actions/upload-artifact@v1
      with:
        name: drop
        path: c:\opt\install
